version: '3.9'

services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=${ORACLE_PWD}
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      ${NETWORK_NAME}:
        ipv4_address: ${ORACLE_DB_IP}

  tomcat:
    build:
      context: ./tomcat
      args:
        ORDS_VERSION: ${ORDS_VERSION}
        ORDS_HOME: ${ORDS_HOME}
        ORDS_CONFIG: ${ORDS_CONFIG}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_SERVICE: ${DB_SERVICE}
        SYS_PASSWORD: ${SYS_PASSWORD}
        APEX_USER: ${APEX_USER}
    container_name: tomcat-ords
    ports:
      - "8080:8080"
    volumes:
      - ./ords_config:/etc/ords/config
      - ./appfiles:/usr/local/tomcat/webapps/appfiles
    depends_on:
      - oracle-db
    environment:
      - TZ=${TZ}
    networks:
      ${NETWORK_NAME}:
        ipv4_address: ${TOMCAT_IP}

volumes:
  oracle_data:

networks:
  ${NETWORK_NAME}:
    name: ${NETWORK_NAME}
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
          ip_range: ${IP_RANGE}
          gateway: ${GATEWAY}